src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Lifetime_Is_Major_Giver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</description>
        <inlineHelpText>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</inlineHelpText>
        <label>Lifetime Major Giver?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/CampaignMember_SetArchiveBatchable.cls
global class CampaignMember_SetArchiveBatchable implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext batchableContext){
        return Database.getQueryLocator([
            select Id
                 , rC_Giving__Archive_Flag__c
                 , Contact.Account.rC_Giving__Lifetime_Is_Major_Giver__c
                 , LastModifiedDate
              from CampaignMember
             where LastModifiedDate >= :Date.today().addYears(-2)
               and Contact.Account.rC_Giving__Lifetime_Is_Major_Giver__c = false
        ]);
    }
    
    global void execute(Database.BatchableContext batchableContext, CampaignMember[] campaignMemberList) {
        for(CampaignMember campaignMember : campaignMemberList)
            campaignMember.rC_Giving__Archive_Flag__c = true;
        update campaignMemberList;
    }
    
    global void finish(Database.BatchableContext batchableContext) {
        
    }
}