src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Lifetime_Is_Major_Giver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</description>
        <inlineHelpText>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</inlineHelpText>
        <label>Lifetime Major Giver?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Amount__c</fullName>
        <description>Manually populated, this field indicates the amount to pledged.</description>
        <label>Giving Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Frequency__c</fullName>
        <description>Frequency that Giving Amount is pledged to be given (Giving Frequency of Quarterly and Giving Amount of $25 means that $100 is pledged)</description>
        <inlineHelpText>Frequency that Giving Amount is pledged to be given (Giving Frequency of Quarterly and Giving Amount of $25 means that $100 is pledged)</inlineHelpText>
        <label>Giving Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Payment_Frequency__c</fullName>
        <description>Expected timing of payments from donor.</description>
        <inlineHelpText>Expected timing of payments from donor.</inlineHelpText>
        <label>Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Inventory__Check_Inventory_Levels__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Used to check inventory if item can be awarded. To award item when no inventory is available, uncheck field.</inlineHelpText>
        <label>Check Inventory Levels</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/OpportunityLineItem_SetArchiveBatchable.cls
global class OpportunityLineItem_SetArchiveBatchable implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext batchableContext){
        return Database.getQueryLocator([
            select Id
                 , rC_Giving__Archive_Flag__c
              from OpportunityLineItem
             where Opportunity.rC_Giving__Archive_Flag__c = true
        ]);
    }
    
    global void execute(Database.BatchableContext batchableContext, OpportunityLineItem[] opportunityLineItemList) {
        for(OpportunityLineItem opportunityLineItem : opportunityLineItemList)
            opportunityLineItem.rC_Giving__Archive_Flag__c = true;
        update opportunityLineItemList;
    }
    
    global void finish(Database.BatchableContext batchableContext) {
        
    }
    
    @IsTest(SeeAllData = true)
    public static void test() {
        Account account = new Account();
        account.name = 'Account Name';
        account.rC_Giving__Lifetime_Is_Major_Giver__c = false;
        insert account;
        
        System.assert(null != account.Id, 'OpportunityLineItem_SetArchiveBatchable.test() : Account record insertion is failed'+account);
        
        Campaign campaign = new Campaign(Name = 'Campaign Name');
        insert campaign;
        
        System.assert(null != campaign.Id, 'OpportunityLineItem_SetArchiveBatchable.test() : Campaign record insertion is failed'+campaign);
        
        Opportunity opportunity = new Opportunity();
        opportunity.AccountId = account.Id;
        opportunity.CampaignId = campaign.Id;
        opportunity.Name = 'Opportunity Name';
        opportunity.StageName = 'Closed';
        opportunity.CloseDate = Date.today();
        opportunity.rC_Giving__Archive_Flag__c = true;
        opportunity.rC_Giving__Giving_Amount__c = 10;
        opportunity.rC_Giving__Giving_Frequency__c = 'One Payment';
        opportunity.rC_Giving__Payment_Frequency__c = 'One Payment';
        insert opportunity;
        
        System.assert(null != opportunity.Id, 'OpportunityLineItem_SetArchiveBatchable.test() : Opportunity record insertion is failed'+opportunity);
        
        Pricebook2 pricebookStandard = [
            select Id
              from Pricebook2
             where IsStandard = true
             limit 1
        ];
         
        Product2 product1 = new Product2();
        product1.Name = 'RCSBIRD Product1';
        product1.ProductCode = 'TEST1';
        product1.Family = null;
        product1.rC_Inventory__Check_Inventory_Levels__c = false;
        insert product1;
        
        System.assert(null != product1.Id, 'OpportunityLineItem_SetArchiveBatchable.test() : Product record insertion is failed'+product1);
        
        // Add to the standard pricebook
        PricebookEntry stdPricebookEntry1 = new PricebookEntry();
        stdPricebookEntry1.Pricebook2Id = pricebookStandard.Id;
        stdPricebookEntry1.Product2Id = product1.Id;
        stdPricebookEntry1.UnitPrice = 10;
        stdPricebookEntry1.UseStandardPrice = false;
        stdPricebookEntry1.IsActive = true;
        insert stdPricebookEntry1;
        
        System.assert(null != stdPricebookEntry1.Id, 'OpportunityLineItem_SetArchiveBatchable.test() : PriceBookEntry record insertion is failed'+stdPricebookEntry1);
        
        OpportunityLineItem opportunityLineItem = new OpportunityLineItem();
        opportunityLineItem.OpportunityId = opportunity.Id;
        opportunityLineItem.PricebookEntryId = stdPricebookEntry1.Id;
        opportunityLineItem.Quantity = 1;
        opportunityLineItem.UnitPrice = 10;
        insert opportunityLineItem;
        
        System.assert(null != opportunityLineItem.Id, 'OpportunityLineItem_SetArchiveBatchable.test() : OpportunityLineItem record insertion is failed'+opportunityLineItem);
        
        System.assertEquals(false, [select rC_Giving__Archive_Flag__c from OpportunityLineItem where Id =: opportunityLineItem.Id].rC_Giving__Archive_Flag__c, 'OpportunityLineItem_SetArchiveBatchable.test() : Archived OpportunityLineItem record inserted'+opportunityLineItem);
        Test.startTest();
        System.assert(true, Database.executeBatch(new OpportunityLineItem_SetArchiveBatchable(), 1) != null);
        Test.stopTest();
        System.assertEquals(true, [select rC_Giving__Archive_Flag__c from OpportunityLineItem where Id =: opportunityLineItem.Id].rC_Giving__Archive_Flag__c, 'OpportunityLineItem_SetArchiveBatchable.test() : OpportunityLineItem record updation is failed'+opportunityLineItem);
    }
}