src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Lifetime_Is_Major_Giver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</description>
        <inlineHelpText>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</inlineHelpText>
        <label>Lifetime Major Giver?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/Case_SetArchiveBatchableTest.cls
@isTest
public class Case_SetArchiveBatchableTest {
    @isTest
    public static void test() {
        Account account = new Account();
        account.name = 'Account Name';
        account.rC_Giving__Lifetime_Is_Major_Giver__c = false;
        insert account;
        
        System.assert(null != account.Id, 'Case_SetArchiveBatchableTest.test() : Account record insertion is failed'+account);
        
        Case caseObj = new Case();
        caseObj.AccountId = account.Id;
        caseObj.Origin = 'Email';
        caseObj.Status = 'Closed';
        insert caseObj;
        
        System.assert(null != caseObj.Id, 'Case_SetArchiveBatchableTest.test() : Case record insertion is failed'+caseObj);
        
        System.assertEquals(false, [select rC_Bios__Archive_Flag__c from Case where Id =: caseObj.Id].rC_Bios__Archive_Flag__c, 'Case_SetArchiveBatchableTest.test() : Archived Case record inserted'+caseObj);
        Test.startTest();
        System.assert(true, Database.executeBatch(new Case_SetArchiveBatchable(), 1) != null);
        Test.stopTest();
        
        // RCSBIRD-3021
        // 
        // Unable to test: The "ClosedDate" field on Case is read only, so we can not specify that during insert call.
        // It automatically takes generated date and time when the case was closed.
        
        System.assertEquals(true, [select rC_Bios__Archive_Flag__c from Case where Id =: caseObj.Id].rC_Bios__Archive_Flag__c, 'Case_SetArchiveBatchableTest.test() : Case record updation is failed'+caseObj);
    }
}