src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Lifetime_Is_Major_Giver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</description>
        <inlineHelpText>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</inlineHelpText>
        <label>Lifetime Major Giver?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/Task_SetArchiveBatchable.cls
global class Task_SetArchiveBatchable implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext batchableContext){
        return Database.getQueryLocator([
            select Id
                 , rC_Bios__Archive_Flag__c
                 , Account.rC_Giving__Lifetime_Is_Major_Giver__c
                 , ActivityDate
              from Task
             where ActivityDate >= :Date.today().addYears(-2)
               and Account.rC_Giving__Lifetime_Is_Major_Giver__c = false
               and Status = 'Completed'
        ]);
    }
    
    global void execute(Database.BatchableContext batchableContext, Task[] taskList) {
        for(Task task : taskList)
            task.rC_Bios__Archive_Flag__c = true;
        update taskList;
    }
    
    global void finish(Database.BatchableContext batchableContext) {
        
    }
}