src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Lifetime_Is_Major_Giver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</description>
        <inlineHelpText>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</inlineHelpText>
        <label>Lifetime Major Giver?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Affiliation__c</fullName>
        <description>Manually populated, this field indicates the Affiliation this Campaign represents.</description>
        <inlineHelpText>Affiliation this Campaign represents.</inlineHelpText>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>Group 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Giving__GAU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Manually populated, this field indicates the General Accounting Unit where gifts and funds associated with this Campaign will be allocated by default.</description>
        <inlineHelpText>General Accounting Unit where gifts and funds associated with this Campaign will be allocated by default.</inlineHelpText>
        <label>General Accounting Unit</label>
        <referenceTo>rC_Giving__GAU__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Type_Engine__c</fullName>
        <description>To override a Giving record&apos;s Giving Type Engine</description>
        <inlineHelpText>To override a Giving record&apos;s Giving Type Engine</inlineHelpText>
        <label>Giving Type Engine</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Media</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Source_Code__c</fullName>
        <description>Source Code of Campaign as generated by rules defined in the Source Codes configuration.</description>
        <inlineHelpText>Source Code of Campaign as generated by rules defined in the Source Codes configuration.</inlineHelpText>
        <label>Source Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Affiliation__c</fullName>
        <description>Represents groups within the organization. Each Affiliation has its own Summary record on Account.</description>
        <inlineHelpText>Represents groups within the organization. Each Affiliation has its own Summary record on Account.</inlineHelpText>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>Group 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Giving__GAU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This value is copied from associated Campaign at gift creation, and can be manually changed if necessary. If the gift should be split across more than one General Accounting Unit - use the Special Allocations related list to specify the split.</description>
        <inlineHelpText>This value is copied from associated Campaign at gift creation, and can be manually changed if necessary. If the gift should be split across more than one General Accounting Unit - use the Special Allocations related list to specify the split.</inlineHelpText>
        <label>General Accounting Unit</label>
        <referenceTo>rC_Giving__GAU__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Amount__c</fullName>
        <description>Manually populated, this field indicates the amount to pledged.</description>
        <label>Giving Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Frequency__c</fullName>
        <description>Frequency that Giving Amount is pledged to be given (Giving Frequency of Quarterly and Giving Amount of $25 means that $100 is pledged)</description>
        <inlineHelpText>Frequency that Giving Amount is pledged to be given (Giving Frequency of Quarterly and Giving Amount of $25 means that $100 is pledged)</inlineHelpText>
        <label>Giving Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Type_Engine__c</fullName>
        <description>Rules used to determine the value of &apos;Calculated Giving Type&apos;.</description>
        <inlineHelpText>Rules used to determine the value of &apos;Calculated Giving Type&apos;.</inlineHelpText>
        <label>Giving Type Engine</label>
        <picklist>
            <picklistValues>
                <fullName>Public Media</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Years__c</fullName>
        <description>Number of years in Pledge timeline. This field is not set directly but by a picklist in the Giving Wizard.</description>
        <inlineHelpText>Number of years in Pledge timeline. This field is not set directly but by a picklist in the Giving Wizard.</inlineHelpText>
        <label>Giving Years</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Payment_Frequency__c</fullName>
        <description>Expected timing of payments from donor.</description>
        <inlineHelpText>Expected timing of payments from donor.</inlineHelpText>
        <label>Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Source_Code__c</fullName>
        <description>Organization defined unique code for associated Campaign. This value is copied from associated Campaign at gift creation.</description>
        <inlineHelpText>Organization defined unique code for associated Campaign. This value is copied from associated Campaign at gift creation.</inlineHelpText>
        <label>Source Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/Allocation_SetArchiveBatchableTest.cls
@isTest
public class Allocation_SetArchiveBatchableTest {
    @isTest
    public static void test() {
        Account account = new Account();
        account.name = 'Account Name';
        account.rC_Giving__Lifetime_Is_Major_Giver__c = false;
        insert account;
        
        System.assert(null != account.Id, 'Allocation_SetArchiveBatchableTest.test() : Account record insertion is failed'+account);
        
        Campaign campaign = new Campaign();
        campaign.Name = 'RCSBIRD Campaign Name';
        campaign.IsActive = true;
        campaign.rC_Giving__Source_Code__c = 'RCSBIRD_TEST';
        campaign.rC_Giving__Affiliation__c = 'RCSBIRD';
        insert campaign;
        System.assert(null != campaign.Id, 'Allocation_DeleteArchivedBatchableTest.test() : Campaign record insertion is failed'+campaign);
        
        Opportunity opportunity = new Opportunity();
        opportunity.rC_Giving__Affiliation__c = 'RCSBIRD';
        opportunity.AccountId = account.Id;
        opportunity.Amount = 0;
        opportunity.CampaignId = campaign.Id;
        opportunity.CloseDate = Date.today();
        opportunity.rC_Giving__Giving_Amount__c = 10;
        opportunity.rC_Giving__Giving_Frequency__c = 'One Payment';
        opportunity.rC_Giving__Giving_Years__c = 1;
        opportunity.rC_Giving__Giving_Type_Engine__c = 'Standard';
        opportunity.rC_Giving__Payment_Frequency__c = 'One Payment';
        opportunity.StageName = 'Closed';
        opportunity.Name = 'Opportunity Name';
        opportunity.rC_Giving__Archive_Flag__c = true;
        insert opportunity;
        
        System.assert(null != opportunity.Id, 'Allocation_SetArchiveBatchableTest.test() : Opportunity record insertion is failed'+opportunity);
        rC_Giving__GAU__c GAU = new rC_Giving__GAU__c();
        GAU.Name = 'GAU Name';
        insert GAU;
        System.assert(null != GAU.Id, 'Allocation_SetArchiveBatchableTest.test() : GAU record insertion is failed'+GAU);
        
        rC_Giving__Opportunity_Allocation__c allocation = new rC_Giving__Opportunity_Allocation__c();
        allocation.rC_Giving__Opportunity__c = opportunity.Id;
        allocation.rC_Giving__GAU__c = GAU.Id;
        allocation.rC_Giving__Distribution__c = 10;
        insert allocation;
        
        System.assert(null != allocation.Id, 'Allocation_SetArchiveBatchableTest.test() : Allocation record insertion is failed'+allocation);
        
        System.assertEquals(false, [select rC_Giving__Archive_Flag__c from rC_Giving__Opportunity_Allocation__c where Id =: allocation.Id].rC_Giving__Archive_Flag__c, 'Allocation_SetArchiveBatchableTest.test() : Archived Allocation record inserted'+allocation);
        Test.startTest();
        System.assert(true, Database.executeBatch(new Allocation_SetArchiveBatchable(), 1) != null);
        Test.stopTest();
        
        System.assertEquals(true, [select rC_Giving__Archive_Flag__c from rC_Giving__Opportunity_Allocation__c where Id =: allocation.Id].rC_Giving__Archive_Flag__c, 'Allocation_SetArchiveBatchableTest.test() : Allocation record updation is failed'+allocation);
    }
}