src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manually populated field indicating is this account active?</description>
        <inlineHelpText>Is this account active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Archive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</description>
        <inlineHelpText>Identifies a record to be archived in roundData and removed from Salesforce. It will reside in roundData for storage and query runs.</inlineHelpText>
        <label>Archive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Category__c</fullName>
        <description>Manually populated field indicating the type of Organization.</description>
        <inlineHelpText>Indicates the type of Organization.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Lifetime_Is_Major_Giver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</description>
        <inlineHelpText>Account is a current Major Giver or was a Major Giver in the past. This field is automatically checked when a major gift comes in and will never be automatically unchecked.</inlineHelpText>
        <label>Lifetime Major Giver?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/Preference_SetArchiveBatchableTest.cls
@isTest
public class Preference_SetArchiveBatchableTest {
    @isTest
    public static void test() {
        Account account = new Account();
        account.name = 'Account Name';
        account.rC_Giving__Lifetime_Is_Major_Giver__c = false;
        insert account;
        
        System.assert(null != account.Id, 'Preference_SetArchiveBatchableTest.test() : Account record insertion is failed'+account);
        
        rC_Bios__Preference__c preference = new rC_Bios__Preference__c();
        preference.rC_Bios__Account__c = account.Id;
        preference.rC_Bios__Category__c = 'Education';
        preference.rC_Bios__Active__c = false;
        insert preference;
        
        System.assert(null != preference.Id, 'Preference_SetArchiveBatchableTest.test() : Preference record insertion is failed'+preference);
        
        System.assertEquals(false, [select rC_Bios__Archive_Flag__c from rC_Bios__Preference__c where Id =: preference.Id].rC_Bios__Archive_Flag__c, 'Preference_SetArchiveBatchableTest.test() : Archived Preference record inserted'+preference);
        Test.startTest();
        System.assert(true, Database.executeBatch(new Preference_SetArchiveBatchable(), 1) != null);
        Test.stopTest();
        System.assertEquals(true, [select rC_Bios__Archive_Flag__c from rC_Bios__Preference__c where Id =: preference.Id].rC_Bios__Archive_Flag__c, 'Preference_SetArchiveBatchableTest.test() : Preference record updation is failed'+preference);
    }
}