src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Track_Hard_Credits__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Track and display Hard Credit information on Account.</description>
        <inlineHelpText>Track and display Hard Credit information on Account.</inlineHelpText>
        <label>Track Hard Credits?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Track_Soft_Credits__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Track and display Soft Credit information on Account.</description>
        <inlineHelpText>Track and display Soft Credit information on Account.</inlineHelpText>
        <label>Track Soft Credits?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Track_Summaries__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Populated by trigger, indicates if Summaries should be tracked.</description>
        <label>Track Summaries?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>StayClassy_ID__c</fullName>
        <label>StayClassy ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Affiliation__c</fullName>
        <description>Manually populated, this field indicates the Affiliation this Campaign represents.</description>
        <inlineHelpText>Affiliation this Campaign represents.</inlineHelpText>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>Group 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Type_Engine__c</fullName>
        <description>To override a Giving record&apos;s Giving Type Engine</description>
        <inlineHelpText>To override a Giving record&apos;s Giving Type Engine</inlineHelpText>
        <label>Giving Type Engine</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Media</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Source_Code__c</fullName>
        <description>Source Code of Campaign as generated by rules defined in the Source Codes configuration.</description>
        <inlineHelpText>Source Code of Campaign as generated by rules defined in the Source Codes configuration.</inlineHelpText>
        <label>Source Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>rC_Giving__Affiliation__c</fullName>
        <description>Represents groups within the organization. Each Affiliation has its own Summary record on Account.</description>
        <inlineHelpText>Represents groups within the organization. Each Affiliation has its own Summary record on Account.</inlineHelpText>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>Group 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Amount__c</fullName>
        <description>Manually populated, this field indicates the amount to pledged.</description>
        <label>Giving Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Frequency__c</fullName>
        <description>Frequency that Giving Amount is pledged to be given (Giving Frequency of Quarterly and Giving Amount of $25 means that $100 is pledged)</description>
        <inlineHelpText>Frequency that Giving Amount is pledged to be given (Giving Frequency of Quarterly and Giving Amount of $25 means that $100 is pledged)</inlineHelpText>
        <label>Giving Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Type_Engine__c</fullName>
        <description>Rules used to determine the value of &apos;Calculated Giving Type&apos;.</description>
        <inlineHelpText>Rules used to determine the value of &apos;Calculated Giving Type&apos;.</inlineHelpText>
        <label>Giving Type Engine</label>
        <picklist>
            <picklistValues>
                <fullName>Public Media</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Giving_Years__c</fullName>
        <description>Number of years in Pledge timeline. This field is not set directly but by a picklist in the Giving Wizard.</description>
        <inlineHelpText>Number of years in Pledge timeline. This field is not set directly but by a picklist in the Giving Wizard.</inlineHelpText>
        <label>Giving Years</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Payment_Frequency__c</fullName>
        <description>Expected timing of payments from donor.</description>
        <inlineHelpText>Expected timing of payments from donor.</inlineHelpText>
        <label>Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Source_Code__c</fullName>
        <description>Organization defined unique code for associated Campaign. This value is copied from associated Campaign at gift creation.</description>
        <inlineHelpText>Organization defined unique code for associated Campaign. This value is copied from associated Campaign at gift creation.</inlineHelpText>
        <label>Source Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/StayClassyTest.cls
@IsTest
public class StayClassyTest {
    
    @IsTest
    public static void stayClassyTest_InnerClasses() {
        Test.startTest();
        StayClassy.Campaign campaign = new StayClassy.Campaign();
        StayClassy.CampaignResponseList campaignResponseList= new StayClassy.CampaignResponseList();
        
        StayClassy.CampaignTicket campaignTicket = new StayClassy.CampaignTicket();
        
        StayClassy.FundraiserResponseList fundraiserResponseList = new StayClassy.FundraiserResponseList();
        StayClassy.Fundraiser fundraiser = new StayClassy.Fundraiser();
        
        StayClassy.DonationResponseList donationResponseList = new StayClassy.DonationResponseList();
        StayClassy.Donation donation = new StayClassy.Donation();
        DateTime dt = donation.donation_date_time;
        
        StayClassy.TeamResponseList teamResponseList = new StayClassy.TeamResponseList();
        StayClassy.Team team = new StayClassy.Team();
        Test.stopTest();
    }
    @IsTest
    public static void stayClassyTest_NullResponseBody() {
        Test.startTest();
        try {
            StayClassy.getEndpointResponse('testEnd', new map<string,string>());
        }
        catch (system.Exception pException) {
            system.assertEquals(true,pException.getMessage().containsIgnoreCase('Empty response body!'));
        }    
        Test.stopTest();
    }
    
    @IsTest
    public static void stayClassyTest_NullProcessMessage() {
        Test.startTest();
        StayClassy stayClassy = new StayClassy();
        stayClassy.processMessage(null, null);
        rC_Messaging__Message__c message1 = new rC_Messaging__Message__c();
        message1.rC_Messaging__Related_Method__c = 'insert';
        message1.rC_Messaging__Related_Record__c = '000001';
        message1.rC_Messaging__Effective_Date__c = DateTime.now();
        stayClassy.processMessage(message1, null);
        Test.stopTest();
    }
    
    @IsTest
    public static void stayClassyTest_EmptyProcessMessageFuture() {
        Test.startTest();
        StayClassy.processMessageFuture(null);
        Test.stopTest();
    }
    @IsTest
    public static void testCampaign_Insert() {
        Test.startTest();
        
        rC_Messaging__Message__c message1 = new rC_Messaging__Message__c();
        message1.rC_Messaging__Endpoint__c = 'stayclassy://campaigns';
        message1.rC_Messaging__Related_Method__c = 'insert';
        message1.rC_Messaging__Related_Record__c = '000001';
        message1.rC_Messaging__Effective_Date__c = DateTime.now();
        insert message1;
        
        StayClassy.schedule();
        StayClassy.addMinutes(DateTime.now(), 0);
        
        Test.stopTest();
    }
    
    @IsTest
    public static void stayClassyTest_NullRelatedMethod() {
        Test.startTest();
        
        rC_Messaging__Message__c message1 = new rC_Messaging__Message__c();
        message1.rC_Messaging__Endpoint__c = 'stayclassy://campaigns';
        message1.rC_Messaging__Related_Record__c = '000001';
        message1.rC_Messaging__Effective_Date__c = DateTime.now();
        insert message1;
        
        StayClassy.schedule();
        StayClassy.addMinutes(DateTime.now(), 0);
        
        Test.stopTest();
    }
    
    @IsTest
    public static void stayClassyTest_UnknownEndpoint() {
        Test.startTest();
        
        rC_Messaging__Message__c message1 = new rC_Messaging__Message__c();
        message1.rC_Messaging__Endpoint__c = 'stayclassy://test';
        message1.rC_Messaging__Related_Method__c = 'insert';
        message1.rC_Messaging__Related_Record__c = '000001';
        message1.rC_Messaging__Effective_Date__c = DateTime.now();
        insert message1;
        
        StayClassy.schedule();
        StayClassy.addMinutes(DateTime.now(), 0);
        
        Test.stopTest();
    }
    
    @IsTest
    public static void stayClassyTest_NullRelatedRecord() {
        Test.startTest();
        
        rC_Messaging__Message__c message1 = new rC_Messaging__Message__c();
        message1.rC_Messaging__Endpoint__c = 'stayclassy://campaigns';
        message1.rC_Messaging__Related_Method__c = 'insert';
        message1.rC_Messaging__Effective_Date__c = DateTime.now();
        insert message1;
        
        StayClassy.schedule();
        StayClassy.addMinutes(DateTime.now(), 0);
        
        Test.stopTest();
    }
    
    @IsTest
    public static void stayClassyTest_UnknownEndpointType() {
        Test.startTest();
        
        rC_Messaging__Message__c message1 = new rC_Messaging__Message__c();
        message1.rC_Messaging__Endpoint__c = 'stayclassy://campaigns';
        message1.rC_Messaging__Related_Method__c = 'test';
        message1.rC_Messaging__Related_Record__c = '000001';
        message1.rC_Messaging__Effective_Date__c = DateTime.now();
        insert message1;
        
        StayClassy.schedule();
        StayClassy.addMinutes(DateTime.now(), 0);
        
        Test.stopTest();
    }
    @IsTest
    public static void testFundraiser_Insert() {
        Test.startTest();
        
        rC_Messaging__Message__c message2 = new rC_Messaging__Message__c();
        message2.rC_Messaging__Endpoint__c = 'stayclassy://fundraisers';
        message2.rC_Messaging__Related_Method__c = 'insert';
        message2.rC_Messaging__Related_Record__c = '000002';
        message2.rC_Messaging__Effective_Date__c = DateTime.now();
        insert message2;
        
        Test.stopTest();
    }
    
    @IsTest
    public static void testTeam_Insert1() {
        Test.startTest();
        
        rC_Messaging__Message__c message3 = new rC_Messaging__Message__c();
        message3.rC_Messaging__Endpoint__c = 'stayclassy://teams';
        message3.rC_Messaging__Related_Method__c = 'insert';
        message3.rC_Messaging__Related_Record__c = '000003';
        message3.rC_Messaging__Effective_Date__c = DateTime.now();
        insert message3;
        
        Test.stopTest();
    }
    
    //@IsTest
    public static void testTeam_Insert2() {
        Test.startTest();
        
        rC_Messaging__Message__c message4 = new rC_Messaging__Message__c();
        message4.rC_Messaging__Endpoint__c = 'stayclassy://teams';
        insert message4;
        
        Test.stopTest();
    }
    
    @IsTest
    public static void testDonation_Insert() {
        Test.startTest();
        
        Account account4 = new Account();
        account4.Name = 'RCSBIRD Account';
        account4.rC_Giving__Track_Hard_Credits__c = true;
        account4.rC_Giving__Track_Soft_Credits__c = true;
        account4.rC_Giving__Track_Summaries__c = true;
        insert account4;
        
        Campaign campaign4 = new Campaign();
        campaign4.Name = 'RCSBIRD Campaign Name';
        campaign4.IsActive = true;
        campaign4.rC_Giving__Source_Code__c = 'RCSBIRD_TEST';
        campaign4.rC_Giving__Affiliation__c = 'RCSBIRD';
        insert campaign4;
        
        Opportunity opportunity4 = new Opportunity();
        opportunity4.rC_Giving__Affiliation__c = 'RCSBIRD';
        opportunity4.AccountId = account4.Id;
        opportunity4.Amount = 0;
        opportunity4.CampaignId = campaign4.Id;
        opportunity4.CloseDate = Date.today();
        opportunity4.rC_Giving__Giving_Amount__c = 100;
        opportunity4.rC_Giving__Giving_Frequency__c = 'One Payment';
        opportunity4.rC_Giving__Giving_Years__c = 1;
        opportunity4.rC_Giving__Giving_Type_Engine__c = 'Standard';
        opportunity4.rC_Giving__Payment_Frequency__c = 'One Payment';
        opportunity4.RecordTypeId = rC_Giving.OpportunityRecordTypes.RT_MEMBERSHIP_ID;
        opportunity4.StageName = 'Open';
        insert opportunity4;
        
        opportunity4.StayClassy_ID__c = opportunity4.Id;
        update opportunity4;
        
        rC_Messaging__Message__c message5 = new rC_Messaging__Message__c();
        message5.rC_Messaging__Endpoint__c = 'stayclassy://donations';
        message5.rC_Messaging__Related_Method__c = 'insert';
        message5.rC_Messaging__Related_Record__c = opportunity4.Id;
        insert message5;
        
        Test.stopTest();
    }
}