src/objects/Archival__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Database__c</fullName>
        <description>roundData database name (used to retrieve archive records)</description>
        <inlineHelpText>roundData database name (used to retrieve archive records)</inlineHelpText>
        <label>Database</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>restapi_Opportunity__c</fullName>
        <description>the RESTAPI URL for the Opportunity object</description>
        <inlineHelpText>the RESTAPI URL for the Opportunity object</inlineHelpText>
        <label>restapi_Opportunity</label>
        <type>Url</type>
    </fields>
    <label>Archival</label>
</CustomObject>

src/classes/Account_ManageGivingArchivalTest.cls
@IsTest
public class Account_ManageGivingArchivalTest {
    @IsTest
    public static void testManageGivingArchival() {
        Account account = new Account();
        account.name = 'Account Name';
        insert account;
        
        Archival__c archivalSetting = Archival__c.getInstance();
        archivalSetting.Database__c = 'RC_LABS';
        archivalSetting.RESTful_Host__c = 'http://54.243.143.26:8080/rC_Archival/';
        archivalSetting.RESTapi_Opportunity__c = '/Opportunity/GetAccount?accountId=';
        upsert archivalSetting;
        
        System.assert(null != account.Id, 'Account_ViewArchivedDataTest.testViewArchivedData() : Account record insertion is failed'+account);
        
        Account_ManageGivingArchival accountExtension = new Account_ManageGivingArchival(new ApexPages.StandardController(account));
        
        accountExtension.putParam('objectName','Opportunity');
        accountExtension.initialize();
        
        system.assertNotEquals(null, accountExtension.dataList, 'Account_ViewArchivedDataTest.testViewArchivedData() : Data list initialization failed');
    }
}