src/objects/Archival__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Database__c</fullName>
        <description>roundData database name (used to retrieve archive records)</description>
        <inlineHelpText>roundData database name (used to retrieve archive records)</inlineHelpText>
        <label>Database</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>restapi_OpportunityLineItem__c</fullName>
        <description>the RESTAPI URL for OpportunityLineItem object</description>
        <inlineHelpText>the RESTAPI URL for OpportunityLineItem object</inlineHelpText>
        <label>restapi_OpportunityLineItem</label>
        <type>Url</type>
    </fields>
    <label>Archival</label>
</CustomObject>

src/classes/Opportunity_ViewArchivedGivingItemTest.cls
@IsTest
public class Opportunity_ViewArchivedGivingItemTest {
    @IsTest
    public static void testViewArchivedData() {
        rC_LabsGivingTests rc = new rC_LabsGivingTests();
        rc.initializeAccount();
        rc.initializeCampaign(true);
        rc.initializeOpportunity(true);
        
        Archival__c archivalSetting = Archival__c.getInstance();
        archivalSetting.Database__c = 'RC_LABS';
        archivalSetting.RESTful_Host__c = 'http://54.243.143.26:8080/rC_Archival/';
        archivalSetting.RESTapi_OpportunityLineItem__c = '/OpportunityLineItem/GetOpportunity?OpportunityID=';
        upsert archivalSetting;
        
        Account_ManageGivingArchival accountArchival = new Account_ManageGivingArchival(new ApexPages.StandardController(rc.account));
        accountArchival.initialize();
        PageReference archivedDataViewRef = accountArchival.getItemsLink();
        system.assertNotEquals(null, archivedDataViewRef, 'Opportunity_ViewArchivedGivingItemTest.testViewArchivedData() : Invalid redirection');
        
        Test.setCurrentPageReference(archivedDataViewRef);
        Opportunity_ViewArchivedGivingItem opportunityExtension = new Opportunity_ViewArchivedGivingItem(new ApexPages.StandardController(rc.opportunity));
        
        opportunityExtension.initialize();
        system.assertNotEquals(null, opportunityExtension.dataList, 'Opportunity_ViewArchivedGivingItemTest.testViewArchivedData() : Data initialization failed');
    }
}