src/objects/Archival__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Database__c</fullName>
        <description>roundData database name (used to retrieve archive records)</description>
        <inlineHelpText>roundData database name (used to retrieve archive records)</inlineHelpText>
        <label>Database</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>restapi_Opportunity__c</fullName>
        <description>the RESTAPI URL for the Opportunity object</description>
        <inlineHelpText>the RESTAPI URL for the Opportunity object</inlineHelpText>
        <label>restapi_Opportunity</label>
        <type>Url</type>
    </fields>
    <label>Archival</label>
</CustomObject>

src/classes/Account_ManageGivingTreeTest.cls
@IsTest
public class Account_ManageGivingTreeTest {
    @IsTest
    public static void test() {
        rC_LabsGivingTests rc = new rC_LabsGivingTests();
        rc.initializeAccount();
        rc.initializeCampaign(true);
        rc.initializeOpportunity(true);
        
        Archival__c archivalSetting = Archival__c.getInstance();
        archivalSetting.Database__c = 'RC_LABS';
        archivalSetting.RESTful_Host__c = 'http://54.243.143.26:8080/rC_Archival/';
        archivalSetting.RESTapi_Opportunity__c = '/Opportunity/GetAccount?accountId=';
        upsert archivalSetting;
        
        Account_ManageGivingTree accountExtension = new Account_ManageGivingTree(new ApexPages.StandardController(rc.account));
        accountExtension.initialize();
        
        system.assertEquals(true, accountExtension.showOpportunityArchival, 'Account_ManageGivingTree.initialize() Archival setting Initialisation check fails');
        system.assertEquals(true, accountExtension.account != null, 'Account_ManageGivingTree.initialize() Account Initialisation check fails');
        system.assertEquals(true, accountExtension.opportunityList != null, 'Account_ManageGivingTree.initialize() opportunityList Initialisation check fails');
        system.assertEquals(true, accountExtension.opportunityDataList != null, 'Account_ManageGivingTree.initialize() opportunityDataList Initialisation check fails');
        system.assertEquals(true, accountExtension.timelineDataList != null, 'Account_ManageGivingTree.initialize() timelineDataList Initialisation check fails');
        
        accountExtension.redirectToHideTransactions();
        accountExtension.redirectToShowTransactions();
        system.assertNotEquals(null, accountExtension.redirectToShowArchivedGiving().getUrl(), 'Account_ManageGivingTreeTest.test() : Redirection to Archived Giving View page fails');
    }
}